# Temel imaj olarak resmi Nginx web sunucusunu (en son sürüm) kullanıyoruz.
FROM nginx:latest

# Bulunduğumuz dizindeki statik dosyaları (.html, .css vb.) 
# Nginx'in varsayılan web sunucu klasörüne kopyalıyoruz.
COPY . /usr/share/nginx/html
